name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Read version from VERSION file
      id: read_version
      run: echo "::set-output name=version::$(cat VERSION)"
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag michav1/ui:${{ steps.read_version.outputs.version }}
    
    - name: Log in to Docker Hub
      run: docker login -u "michav1" -p "DiamondInTheRough"
    
    - name: Push Docker image to Docker Hub
      run: docker push michav1/ui:${{ steps.read_version.outputs.version }}
